name: Deploy
run-name: "Deploying to ${{ github.event.inputs.environment }} ${{ github.event.inputs.target }}"

env:
  TARGET_BASE_PATH: "c$/dev"
  SERVICE_DIR: "${{ github.event.repository.name }}"
  JOB_NAME: "${{ github.event.repository.name }}"

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: choice
        options:
          - production
          - dev
      build_before:
        description: 'Build before deploy?'
        required: true
        type: boolean
        default: true
      target:
        description: 'Specific target server (domain name or address)'
        required: true
        type: string
        default: 'BS309'

jobs:
  build:
    # This job will only run if 'build_before' is checked
    if: ${{ github.event.inputs.build_before == 'true' }}
    uses: ./.github/workflows/build.yml
    
  deploy:
    runs-on: [self-hosted, windows, x64]
    needs: build
    if: ${{ always() && needs.build.result != 'failure' }}
    env:
      target: ${{ github.event.inputs.target }}
    steps:  
      - name: "Deploying to ${{ env.target }} as ${{ github.event.inputs.environment }}"
        run: echo "run ${{ github.run_number }} ..." 
     
      - name: "Copy 'Release' folder"
        run: |
          $sourcePath = "${{ env.SERVICE_DIR }}/bin/Release/net8.0"
          $targetPath = "\\${{ env.target }}\${{ env.TARGET_BASE_PATH }}\${{ env.JOB_NAME }}\r${{ github.run_number }}\"
          echo "Deploying to $targetPath"
          if (!(Test-Path -Path $targetPath)) {
            New-Item -ItemType Directory -Force -Path $targetPath
          }     
          Copy-Item -Path "$sourcePath\*" -Destination "$targetPath" -Recurse
      